### ISSUE TITLE
render_to_response in views.py

### ISSUE THREAD

**Issue by OHDMax** [captainkingcandy/django-dynamic-link#1]
Hallo @captainkingcandy,

hier steht noch ein deprecated `render_to_response`, welches die Anzeige von abgelaufenen Links fehlschlagen lässt:
https://github.com/captainkingcandy/django-dynamic-link/blob/f1d52e74c658a9230c339bdf85d730863156e555/dynamicLink/views.py#L40

**Comment by captainkingcandy** [comment]
Oh tatsache, sollte jetzt gefixt sein! Vielen dank ;-)
